version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: ./script/start
    volumes:
      - .:/myapp
    volumes_from:
      - box
    ports:
      - "3000:3000"
    depends_on:
      - db
  box:
    image: busybox
    volumes:
      - /box
